config/routes.rb
Rails.application.routes.draw do
  resources :balances
  resources :expenditures
  resources :incomes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/balance.rb
class Balance < ApplicationRecord
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord

  # 年収の合計メソッド
  # 1年ごとの合計メソッド
  # def total_annual_income
  # end

  # カテゴリごとの合計メソッド
  # def total_income_by_category
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :set_balance, only: %i[ show edit update destroy ]

  # GET /balances or /balances.json
  def index
    @balances = Balance.all
  end

  # GET /balances/1 or /balances/1.json
  def show
  end

  # GET /balances/new
  def new
    @balance = Balance.new
  end

  # GET /balances/1/edit
  def edit
  end

  # POST /balances or /balances.json
  def create
    @balance = Balance.new(balance_params)

    respond_to do |format|
      if @balance.save
        format.html { redirect_to balance_url(@balance), notice: "Balance was successfully created." }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balances/1 or /balances/1.json
  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to balance_url(@balance), notice: "Balance was successfully updated." }
        format.json { render :show, status: :ok, location: @balance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1 or /balances/1.json
  def destroy
    @balance.destroy

    respond_to do |format|
      format.html { redirect_to balances_url, notice: "Balance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance
      @balance = Balance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_params
      params.require(:balance).permit(:year, :month, :income_id, :expenditure_id)
    end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: %i[ show edit update destroy ]

  # GET /expenditures or /expenditures.json
  def index
    @expenditures = Expenditure.all
  end

  # GET /expenditures/1 or /expenditures/1.json
  def show
  end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
  end

  # GET /expenditures/1/edit
  def edit
  end

  # POST /expenditures or /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to expenditure_url(@expenditure), notice: "Expenditure was successfully created." }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenditures/1 or /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditure_url(@expenditure), notice: "Expenditure was successfully updated." }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: "Expenditure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenditure
      @expenditure = Expenditure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expenditure_params
      params.require(:expenditure).permit(:year, :month, :category, :amount)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[ show edit update destroy ]

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1 or /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes or /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to income_url(@income), notice: "Income was successfully created." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to income_url(@income), notice: "Income was successfully updated." }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: "Income was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:year, :month, :category, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/balances/_balance.html.erb
<div id="<%= dom_id balance %>">
  <p>
    <strong>Year:</strong>
    <%= balance.year %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= balance.month %>
  </p>

  <p>
    <strong>Income:</strong>
    <%= balance.income_id %>
  </p>

  <p>
    <strong>Expenditure:</strong>
    <%= balance.expenditure_id %>
  </p>

</div>

app/views/balances/_form.html.erb
<%= form_with(model: balance) do |form| %>
  <% if balance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(balance.errors.count, "error") %> prohibited this balance from being saved:</h2>

      <ul>
        <% balance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.number_field :month %>
  </div>

  <div>
    <%= form.label :income_id, style: "display: block" %>
    <%= form.number_field :income_id %>
  </div>

  <div>
    <%= form.label :expenditure_id, style: "display: block" %>
    <%= form.number_field :expenditure_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/balances/edit.html.erb
<h1>Editing balance</h1>

<%= render "form", balance: @balance %>

<br>

<div>
  <%= link_to "Show this balance", @balance %> |
  <%= link_to "Back to balances", balances_path %>
</div>

app/views/balances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Balances</h1>

<div id="balances">
  <% @balances.each do |balance| %>
    <%= render balance %>
    <p>
      <%= link_to "Show this balance", balance %>
    </p>
  <% end %>
</div>

<%= link_to "New balance", new_balance_path %>

app/views/balances/new.html.erb
<h1>New balance</h1>

<%= render "form", balance: @balance %>

<br>

<div>
  <%= link_to "Back to balances", balances_path %>
</div>

app/views/balances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @balance %>

<div>
  <%= link_to "Edit this balance", edit_balance_path(@balance) %> |
  <%= link_to "Back to balances", balances_path %>

  <%= button_to "Destroy this balance", @balance, method: :delete %>
</div>

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">
  <p>
    <strong>Category:</strong>
    <%= expenditure.category %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expenditure.amount %>
  </p>

</div>

app/views/expenditures/_form.html.erb
<%= form_with(model: expenditure) do |form| %>
  <% if expenditure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
        <% expenditure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>
  
  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.number_field :month %>
  </div>
  
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Show this expenditure", @expenditure %> |
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenditures</h1>

<div id="expenditures">
  <% @expenditures.each do |expenditure| %>
    <%= render expenditure %>
    <p>
      <%= link_to "Show this expenditure", expenditure %>
    </p>
  <% end %>
</div>

<%= link_to "New expenditure", new_expenditure_path %>

app/views/expenditures/new.html.erb
<h1>New expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expenditure %>

<div>
  <%= link_to "Edit this expenditure", edit_expenditure_path(@expenditure) %> |
  <%= link_to "Back to expenditures", expenditures_path %>

  <%= button_to "Destroy this expenditure", @expenditure, method: :delete %>
</div>

app/views/incomes/_form.html.erb
<%= form_with(model: income) do |form| %>
  <% if income.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>
  
  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.number_field :month %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>">
  <p>
    <strong>Category:</strong>
    <%= income.category %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= income.amount %>
  </p>

</div>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Show this income", @income %> |
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_income_path(@income) %> |
  <%= link_to "Back to incomes", incomes_path %>

  <%= button_to "Destroy this income", @income, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="inner">
    <p class="logo"><a class="over" href="#">お金の管理サイト</a></p>
    <ul class="navi">
      <li><a href="/1/">その１</a></li>
      <li><a href="/2/">その２</a></li>
      <li><a href="/3/">その３</a></li>
      <li><a href="/4/">その４</a></li>
      <li><a href="/5/">その５</a></li>
    </ul>
  </div>
  <button class="sp-navi-toggle">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="menu">MENU</span>
    <span class="close">CLOSE</span></button>
</header>

<style>
/* header */

header {
  position: fixed;
  z-index: 999;
  top: 0;
  left: 0;
  width: 100%;
  padding: 20px 0;
  background: #eee;
}
header .inner {
  position: relative;
  padding: 0 20px;
  display: flex;
  align-items: center;
  height: 100%;
}
/* .logo */

header .logo {
  position: relative;
  width: 200px;
  margin: 0;
  padding: 0;
}
header .logo a {
  font-weight: bold;
  text-decoration: none;
  color: #333;
}

@media screen and (max-width: 767px) {
  header .logo {
    padding: 0;
  }
  header .logo a {
  }
}

/* scroll */

header {
  transition: height 0.4s cubic-bezier(0.34, 0.615, 0.4, 0.985);
}
header.scroll {
  height: 60px;
  position: fixed;
  z-index: 9999;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}
header .logo {
  transition: width 0.4s cubic-bezier(0.34, 0.615, 0.4, 0.985);
}
header.scroll .logo {
  width: 70px;
}

/* header-navi-box */

header .navi {
  margin: 0 0 0 auto;
  padding: 0;
  font-size: 14px;
  font-weight: bold;
  display: flex;
  list-style: none;
}
header .navi li {
  margin: 5px 0 5px 40px;
}
header .navi li:first-child {
  margin-left: 0;
}
header .navi li a {
  display: block;
  box-sizing: border-box;
  text-decoration: none;
  color: #333;
}
header .navi li a:hover {
  text-decoration: underline;
}

@media screen and (max-width: 767px) {
  header .navi {
    display: none;
  }
}

/* open-button */

.sp-navi-toggle {
  display: none;
  margin: auto 0;
  font-size: 10px;
  font-weight: bold;
  line-height: 1;
  position: absolute;
  top: 0;
  bottom: 0;
  right: 40px;
  width: 16px;
  height: 25px;
  transition: all 0.4s;
  color: #464646;
  border: none;
  outline: none;
  background: none;
  -webkit-appearance: unset;
}
.sp-navi-toggle .menu,
.sp-navi-toggle .close {
  position: absolute;
  bottom: 0;
  left: -50%;
  display: block;
  width: 34px;
  height: 11px;
}
.sp-navi-toggle .close {
  display: none;
}
.sp-navi-toggle .bar {
  position: absolute;
  left: 0;
  width: 100%;
  height: 2px;
  background-color: #464646;
}
.sp-navi-toggle .bar:nth-of-type(1) {
  top: 0;
}
.sp-navi-toggle .bar:nth-of-type(2) {
  top: 5px;
}
.sp-navi-toggle .bar:nth-of-type(3) {
  top: 10px;
}

/* close-button */

html.sidebar-is-open .sp-navi-toggle .bar:nth-of-type(1) {
  top: 5px;
  transform: rotate(45deg);
}
html.sidebar-is-open .sp-navi-toggle .bar:nth-of-type(2) {
  top: 5px;
  transform: rotate(-45deg);
}
html.sidebar-is-open .sp-navi-toggle .bar:nth-of-type(3) {
  display: none;
}
html.sidebar-is-open .sp-navi-toggle .menu {
  display: none;
}
html.sidebar-is-open .sp-navi-toggle .close {
  display: block;
}

@media screen and (max-width: 767px) {
  .sp-navi-toggle{
    display: block;
  }
}

/* sp-navi */

.sp-navi-box {
  display: none;
}
.sp-navi {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  list-style: none;
  width: 100%;
  height: 100vh;
  font-size: 14px;
  margin: 0;
  padding: 0;
}
.sp-navi li {
  padding: 20px 0;
}
.sp-navi li a {
  display: block;
  box-sizing: border-box;
  text-decoration: none;
  color: #333;
  font-weight: bold;
}
.sp-navi li a:hover {
  text-decoration: underline;
}




@media screen and (max-width: 767px) {
  html.sidebar-is-open .sp-navi-box {
    display: block;
  }
  html.sidebar-is-open {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow: hidden;
    width: 100%;
  }
}

body {
  margin-top: 80px;
  padding: 0;
}
</style>

<script>
//sp menu

(function () {
  document
    .querySelector("body")
    .insertAdjacentHTML("afterbegin", '<div class="sp-navi-box"><div class="sp-navi"></div></div>');
  document.querySelector(".sp-navi").innerHTML = document.querySelector(
    ".navi"
  ).innerHTML;

  const documentElement = document.querySelector("html");
  const contentElement = document.querySelector("#main");
  const sidebarElement = document.querySelector(".sp-navi-box");
  const openSidebar = function () {
    scl_point = window.pageYOffset;
    documentElement.classList.add("sidebar-is-open");
    $("body").css("top", "-" + scl_point + "px");
  };
  const closeSidebar = function () {
    documentElement.classList.remove("sidebar-is-open");
    $(window).scrollTop(
      $("body").css("top").replace(/-/g, "").replace(/px/g, "")
    );
    $("body").css("top", 0);
  };
  $(".sp-navi-toggle").click(function () {
    //, .sp-navi-box a[href^=#]
    if ($(".sidebar-is-open").length) {
      closeSidebar();
    } else {
      openSidebar();
    }
  });
})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render 'layouts/header' %>
  
  <body>
    <%= yield %>
  </body>
</html>